version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flask_log_vote_server.py
      - FLASK_ENV=development
    volumes:
      - ./app:/app
